---
title: "Measuring Voters' Knowledge of the Electoral System and Behavior Analysis of Electoral Alliances"
author: 
  - Duman, Enes[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080481, [Github Repo](https://github.com/dumanenes3/Midterm)


# Introduction
In Turkey, "Presidential Election and 28th Term General Election of Members of Parliament" will be held on May 14th, 2023. The current electoral system forces political parties to form alliances. Especially for parties that cannot enter parliament, the only way to exceed the 7% electoral threshold is to form a "power alliance". According to the current system, if the total vote of the alliance exceeds 7%, all parties that form the alliance are considered to have exceeded the threshold. However, another problem arises due to the D'Hondt system, as political parties forming an alliance and exceeding the threshold may still not be able to enter parliament due to this system.

There are many technical parameters behind the formation of electoral alliances. While politicians should not ignore cultural, political, and ideological differences when forming alliances, focusing more on technical issues can confuse voters. The research topic is to investigate the existence of this confusion among voters in Turkey. Do voters have sufficient knowledge about the current electoral system? Would the election outcome be affected if voters had more information about the system?

To answer these questions, a survey was conducted with 63 participants from 9 different provinces in Turkey, from different age, gender, education, income, and occupation groups. Participants under the age of 18 will not be taken into account (the voting age in Turkey is 18). In the survey, voters were asked personal questions such as age, gender, education level, annual household income, occupation, as well as questions about the electoral threshold percentage for the upcoming May 14th elections, whether they had heard of the D'Hondt system before, whether the political party they support is part of an alliance, what decision they would make if the political party they support makes a decision contrary to their beliefs, and how many members of parliament will be elected from their province.



## Literature Review

As it is a current topic, the literature is not yet sufficiently rich. More scientific articles will be published before and after the election. In the next stages of the study, more use can be made of the literature.

\newpage
# References {#references}
<div id="refs"></div>

